a = int(input("첫번째 숫자 입력 : "))
b = int(input("두번째 숫자 입력 : "))
result = a + b
print(a, "+", b, "=", result)
result = a - b
print(a, "-", b, "=", result)
result = a * b
print(a, "*", b, "=", result)
result = a / b
print(a, "/", b, "=", result) 